export const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST';

export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';

export const UNDELETE_TODO_ERROR = 'UNDELETE_TODO_ERROR';

export const UPDATE_TODO_ERROR = 'UPDATE_TODO_ERROR';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';

export const FILTER_TODOS = 'FILTER_TODOS';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const UNLOAD_TODOS_SUCCESS = 'UNLOAD_TODOS_SUCCESS';