
export const  CREATE_BOARD ='CREATE_BOARD'
export const  SHARE_BOARD ='SHARE_BOARD'
export const  GET_BOARD ='GET_BOARD'
export const  UPDATE_BOARD ='UPDATE_BOARD'

export const  GET_BOARDS_SUCCESS ='GET_BOARDS_SUCCESS'
export const  GET_BOARDS_PENDING ='GET_BOARDS_PENDING'
export const  GET_BOARDS_ERROR ='GET_BOARDS_ERROR'

export const  UPDATE_BOARD_SUCCESS ='UPDATE_BOARD_SUCCESS'
export const  UPDATE_BOARD_PENDING ='UPDATE_BOARD_PENDING'
export const  UPDATE_BOARD_ERROR ='UPDATE_BOARD_ERROR'

export const  GET_BOARD_SUCCESS ='GET_BOARD_SUCCESS'
export const  GET_BOARD_PENDING ='GET_BOARD_PENDING'
export const  GET_BOARD_ERROR ='GET_BOARD_ERROR'

export const  CREATE_BOARD_SUCCESS ='CREATE_BOARD_SUCCESS'
export const  CREATE_BOARD_PENDING ='CREATE_BOARD_PENDING'
export const  CREATE_BOARD_ERROR ='CREATE_BOARD_ERROR'

export const  AUTH_USER_SET ='AUTH_USER_SET'

export const  USERS_SET ='USERS_SET'
